## Lesson 1 - Deep Learning with Pytorch


### 1. Seed

This is a way to make random predictable, look at this code: 

In [3]:
import random 

random.seed(9001)
print(random.randint(1, 10))

print(random.randint(1, 10))

print(random.randint(1, 10))

print(random.randint(1, 10))

print(random.randint(1, 10))

print(random.randint(1, 10))

print(random.randint(1, 10))

1
5
5
2
10
5
10


Okay now hold on a second and look at this next example

In [24]:
import random 

random.seed(9001)
print(random.randint(1, 10))

print(random.randint(1, 10))

print(random.randint(1, 10))


print(random.randint(1, 10))

print(random.randint(1, 10))

print(random.randint(1, 10))

print(random.randint(1, 10))

1
5
5
2
10
5
10


So what happenned here? How did this randomly generated numbers come out EXACTLY the same? 

This is because we applied the `random.seed()` command. 

This command allows to set the same sequence of random numbers. And this is exactly the same in Pytorch!  


In [5]:
import torch
torch.manual_seed(0)
print(torch.rand(2))

tensor([0.4963, 0.7682])


### 2. Multiplying matrices 

You can multiply tensors by:
1. Using * command
2. Using torch.mm command 

If we multiplied two matrices: (64, 784) * (784, 256) => (64, 256) 
Note that the 784 parameter has to be the same because of that we are always going to shape the matrices around that idea. 


In [37]:

features = torch.rand((1, 5))
weights = torch.rand((1, 5))


first_option = torch.sum(features * weights)

second_option = torch.mm(features, weights.view(5, 1))


In [38]:
print(first_option)
print(second_option)

tensor(0.9591)
tensor([[0.9591]])


Notice that this two answers would've been different if we tried to view both of them, for example

In [39]:

features = torch.rand((1, 5))
weights = torch.rand((1, 5))


first_option = torch.sum(features * weights.view(1, 5))

second_option = torch.mm(features, weights.view(5, 1))


In [40]:
print(first_option)
print(second_option)

tensor(1.3932)
tensor([[1.3932]])


## 3. Datasets

`torchvision` is a helpful package that contains multiple datasets. 

Supposed Datasets include:
1. MNIST
2. Fashion-MNIST


In [46]:
### Run this cell

from torchvision import datasets, transforms

# Define a transform to normalize the data
transform = transforms.Compose([transforms.ToTensor(),
                              transforms.Normalize((0.5,), (0.5,)),
                              ])

# Download and load the training data
trainset = datasets.MNIST('~/.pytorch/MNIST_data/', download=True, train=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=64, shuffle=True)

## 4. Flattering 

-We could change the shape of a tensor 

This remove the dimensionality of the data to the new shape 



In [11]:
images = torch.tensor([[[4, 1], [4, 1]], [[3, 1], [3, 2]]])

flattered = images.view(images.shape[0], -1)

flattered

tensor([[4, 1, 4, 1],
        [3, 1, 3, 2]])

## 5. Softmax

Softmax gives us the probability of the classes gives images. Originally, the network is randomly initialized and therefore approaches random distribution. Softmax is commonly used in multi-class learning problems where a set of features can be related to one of K classes. 

The equation computes the normalized exponential function of all the units in the layer. 

It becomes interesting because we are dealing with 2D elements 

See: https://ljvmiranda921.github.io/notebook/2017/08/13/softmax-and-the-negative-log-likelihood/

In [15]:
import numpy as np
my_list = [1, 2, 3]
total = np.exp(my_list)
total

array([ 2.71828183,  7.3890561 , 20.08553692])

In [20]:
import numpy as np
my_list = torch.tensor([[1, 2], [1, 2], [1, 2]])
total = np.exp(my_list)
new = torch.sum(total, dim=1)

In [21]:
new

tensor([10.1073, 10.1073, 10.1073], dtype=torch.float64)

In [24]:
total/new.view(-1, 1)

tensor([[0.2689, 0.7311],
        [0.2689, 0.7311],
        [0.2689, 0.7311]], dtype=torch.float64)

## 6. Random with Torch

In [52]:
import torch 

def flip_coin():
    x = torch.rand(1)
    if x > 0.5:
        return 1 
    else:
        return 0
    
print(flip_coin())

tensor([0, 8, 1, 9, 6, 1, 0, 2, 9, 4])

In [26]:
torch.LongTensor(10).random_(0, 10)

tensor([0.0885])

# 7. Numpy Tranpose vs view

In [8]:
import numpy as np
matrix = np.array([[1, 2, 3], 
         [5, 6, 7], 
         [3, 2, 1]])
print(matrix.transpose())
print("-" * 9)
print(matrix.reshape(9, 1))
print("-" * 9)


[[1 5 3]
 [2 6 2]
 [3 7 1]]
---------
[[1]
 [2]
 [3]
 [5]
 [6]
 [7]
 [3]
 [2]
 [1]]
---------


## 8. Torchvision and transforms

To resize element you could use `transforms.Resize(number)` 

However, in order to resize more than one elements we could send in a tuple 

`transforms.Resize((number1, number2))`



## 9. Pretrained networks

Taking an existing network that has already learned to extract powerful features and use it as a starting point to learn a new task. 

* It is important to think about the tradeoff between accuracy and speed 
* The number of layers tells us the amount of hidden layers (i.e. `densenet121` has 121 hidden layers)


In [6]:
from torchvision import models
model = models.densenet121(pretrained=True);

/Users/michaelsheinman/anaconda3/lib/python3.6/site-packages/torchvision-0.2.1-py3.6.egg/torchvision/models/densenet.py:212: UserWarning: nn.init.kaiming_normal is now deprecated in favor of nn.init.kaiming_normal_.
